/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaPRJ;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class QLChiTietHD extends javax.swing.JFrame {

    /**
     * Creates new form QLChiTietHD
     */
    public QLChiTietHD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCTHD = new javax.swing.JLabel();
        lblTTHD = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        tfMaHD = new javax.swing.JTextField();
        lblNgayBan = new javax.swing.JLabel();
        tfNgayBan = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        lblTenNV = new javax.swing.JLabel();
        tfTenNV = new javax.swing.JTextField();
        lblMaKH = new javax.swing.JLabel();
        tfMaKH = new javax.swing.JTextField();
        lblTenKH = new javax.swing.JLabel();
        tfTenKH = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        tfSoDT = new javax.swing.JTextField();
        lblSoDT = new javax.swing.JLabel();
        lblTTMatHang = new javax.swing.JLabel();
        lblMaHH = new javax.swing.JLabel();
        tfMaHH = new javax.swing.JTextField();
        lblTenHH = new javax.swing.JLabel();
        tfTenHH = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        tfDonGia = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        lblThanhTien = new javax.swing.JLabel();
        tfThanhTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbHangHoa = new javax.swing.JTable();
        lblTongTien = new javax.swing.JLabel();
        tfTongTien = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi Tiết Hóa Đơn");

        lblCTHD.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblCTHD.setForeground(new java.awt.Color(0, 51, 204));
        lblCTHD.setText("CHI TIẾT HÓA ĐƠN");

        lblTTHD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTTHD.setForeground(new java.awt.Color(255, 51, 51));
        lblTTHD.setText("Thông tin hóa đơn");

        lblMaHD.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblMaHD.setText("Mã hóa đơn");

        tfMaHD.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaHDActionPerformed(evt);
            }
        });

        lblNgayBan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblNgayBan.setText("Ngày bán");

        tfNgayBan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblMaNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblMaNV.setText("Mã nhân viên");

        tfMaNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTenNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTenNV.setText("Tên nhân viên");

        tfTenNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblMaKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblMaKH.setText("Mã khách hàng");

        tfMaKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTenKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTenKH.setText("Tên khách hàng");

        tfTenKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tfDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblDiaChi.setText("Địa chỉ");

        tfSoDT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblSoDT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblSoDT.setText("Số điện thoại");

        lblTTMatHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTTMatHang.setForeground(new java.awt.Color(255, 0, 255));
        lblTTMatHang.setText("Thông tin các mặt hàng");

        lblMaHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblMaHH.setText("Mã hàng hóa");

        tfMaHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTenHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTenHH.setText("Tên hàng hóa");

        tfTenHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDonGia.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblDonGia.setText("Đơn giá");

        tfDonGia.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblSoLuong.setText("Số lượng");

        spnSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        lblThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblThanhTien.setText("Thành tiền");

        tfThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jtbHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Hàng Hóa", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jtbHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbHangHoa);

        lblTongTien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTongTien.setText("Tổng tiền HD");

        tfTongTien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTimKiem.setText("Tìm kiếm mã hàng hóa");

        tfTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        tfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTimKiemKeyReleased(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(lblCTHD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNgayBan)
                                    .addComponent(lblMaNV)
                                    .addComponent(lblTenNV))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaKH)
                        .addGap(32, 32, 32)
                        .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTTMatHang)
                                        .addGap(201, 201, 201))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblMaHH)
                                        .addGap(28, 28, 28)
                                        .addComponent(tfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDonGia)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(301, 301, 301)
                                                .addComponent(lblTenHH)
                                                .addGap(28, 28, 28)
                                                .addComponent(tfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(lblSoLuong)
                                                .addGap(18, 18, 18)
                                                .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblThanhTien)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblTimKiem)
                                        .addGap(36, 36, 36)
                                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTongTien)
                                        .addGap(35, 35, 35)
                                        .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTTHD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(478, 478, 478)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTenKH)
                                        .addComponent(lblDiaChi)
                                        .addComponent(lblSoDT))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(btnThoat))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCTHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTTHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHD)
                    .addComponent(tfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKH)
                    .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKH)
                            .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoDT)
                            .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayBan)
                            .addComponent(tfNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNV)
                            .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblTTMatHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHH)
                    .addComponent(tfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenHH)
                    .addComponent(tfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonGia)
                    .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuong)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThanhTien)
                    .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien)
                    .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiem)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaHDActionPerformed

    }//GEN-LAST:event_tfMaHDActionPerformed

    private void jtbHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbHangHoaMouseClicked
        int i = jtbHangHoa.getSelectedRow();
        TableModel model = jtbHangHoa.getModel();
        tfMaHH.setText(model.getValueAt(i, 0).toString());
        tfTenHH.setText(model.getValueAt(i, 1).toString());
        spnSoLuong.setValue(model.getValueAt(i, 2));
        tfDonGia.setText(model.getValueAt(i, 3).toString());
        tfThanhTien.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jtbHangHoaMouseClicked

    private void timKiem(String query) {
        DefaultTableModel model = (DefaultTableModel) jtbHangHoa.getModel();
        TableRowSorter<DefaultTableModel> tr =  new TableRowSorter<DefaultTableModel>(model);
        jtbHangHoa.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed

    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        QLHoaDon qlhd = new QLHoaDon();
        qlhd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTimKiemKeyReleased
        String query = tfTimKiem.getText().toLowerCase();
        timKiem(query);
    }//GEN-LAST:event_tfTimKiemKeyReleased

     public Connection getConnection() {
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_projectjava?useUnicode=yes&characterEncoding=UTF-8", "root", "");
            return conn;
            
        } catch (SQLException ex) {
            Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    public ArrayList<ChiTietHoaDon> getdanhSachCTHD() {
        ArrayList<ChiTietHoaDon> dscthd = new ArrayList<ChiTietHoaDon>();
        Connection connection = getConnection();
        String sql = "SELECT * FROM `chitiethd` WHERE `maHD` = '"+tfMaHD.getText()+"'";
        Statement st;
        ResultSet rs;
        

        try {
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            ChiTietHoaDon cthd;
            while(rs.next()) {
                cthd = new ChiTietHoaDon(rs.getString("maHD"),rs.getString("maHH"),rs.getInt("soLuong"),rs.getDouble("donGia"),rs.getDouble("thanhTien"));
                dscthd.add(cthd);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dscthd;
    }
      
    //Hàm thực thi các câu truy vấn
    public void excuteQuery(String sql , String message) {
        Connection conn = getConnection();
        Statement st;
        try {
            st = conn.createStatement();
            if(st.executeUpdate(sql) == 1) {
                //Xuất lại jtable sau khi thực hiện truy vấn thành công
                DefaultTableModel model = (DefaultTableModel) jtbHangHoa.getModel();
                model.setRowCount(0);
                xuatDanhSachHangHoa();
                JOptionPane.showMessageDialog(rootPane, "Sản phẩm " + message + " thành công");
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Sản phẩm không " + message);
            }
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
        public void xuatDanhSachHangHoa() {
        ArrayList<ChiTietHoaDon> list = getdanhSachCTHD();
        DefaultTableModel model = (DefaultTableModel) jtbHangHoa.getModel();
        Object[] row = new Object[5];
        for(int i = 0 ; i < list.size(); i++) {
            row[0] = list.get(i).getMaHD();
            row[1] = list.get(i).getMaHH();
            row[2] = list.get(i).getSoLuong();
            row[3] = list.get(i).getDonGia();
            row[4] = list.get(i).getThanhTien();
            model.addRow(row);
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLChiTietHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbHangHoa;
    private javax.swing.JLabel lblCTHD;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaHH;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayBan;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTTHD;
    private javax.swing.JLabel lblTTMatHang;
    private javax.swing.JLabel lblTenHH;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JSpinner spnSoLuong;
    public static javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfDonGia;
    public static javax.swing.JTextField tfMaHD;
    private javax.swing.JTextField tfMaHH;
    public static javax.swing.JTextField tfMaKH;
    public static javax.swing.JTextField tfMaNV;
    public static javax.swing.JTextField tfNgayBan;
    public static javax.swing.JTextField tfSoDT;
    private javax.swing.JTextField tfTenHH;
    public static javax.swing.JTextField tfTenKH;
    public static javax.swing.JTextField tfTenNV;
    private javax.swing.JTextField tfThanhTien;
    private javax.swing.JTextField tfTimKiem;
    public static javax.swing.JTextField tfTongTien;
    // End of variables declaration//GEN-END:variables
}
