/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaPRJ;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class QLHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form QLHangHoa
     */
    public QLHangHoa() {
        initComponents();
        xuatDanhSachHangHoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQLHH = new javax.swing.JLabel();
        lblMaHH = new javax.swing.JLabel();
        tfMaHH = new javax.swing.JTextField();
        lblTenHH = new javax.swing.JLabel();
        tfTenHH = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        lblDonGiaNhap = new javax.swing.JLabel();
        tfDonGiaNhap = new javax.swing.JTextField();
        lblDonGiaBan = new javax.swing.JLabel();
        tfDonGiaBan = new javax.swing.JTextField();
        lblDonGiaBan1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGhiChu = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnResert = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbQLHH = new javax.swing.JTable();
        lblTimKiem = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQLHH.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblQLHH.setForeground(new java.awt.Color(0, 0, 204));
        lblQLHH.setText("QUẢN LÝ HÀNG HÓA");

        lblMaHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblMaHH.setText("Mã hàng hóa");

        tfMaHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblTenHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTenHH.setText("Tên hàng hóa");

        tfTenHH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblSoLuong.setText("Số lượng");

        spnSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDonGiaNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblDonGiaNhap.setText("Đơn giá nhập");

        tfDonGiaNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDonGiaBan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblDonGiaBan.setText("Đơn giá bán");

        tfDonGiaBan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDonGiaBan1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblDonGiaBan1.setText("Ghi chú");

        taGhiChu.setColumns(20);
        taGhiChu.setRows(5);
        jScrollPane1.setViewportView(taGhiChu);

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaPRJ/icoin/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaPRJ/icoin/edit (1).png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaPRJ/icoin/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnResert.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnResert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaPRJ/icoin/refresh.png"))); // NOI18N
        btnResert.setText("Tạo lại");
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaPRJ/icoin/cancel (1).png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jtbQLHH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtbQLHH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hàng Hóa", "Tên Hàng Hóa", "Số Lượng", "Đơn Giá Nhập", "Đơn Giá Bán", "Ghi Chú"
            }
        ));
        jtbQLHH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbQLHHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbQLHH);

        lblTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTimKiem.setText("Tìm Kiếm");

        tfTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        tfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQLHH)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMaHH)
                                    .addGap(38, 38, 38)
                                    .addComponent(tfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTenHH)
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonGiaNhap)
                            .addComponent(lblDonGiaBan)
                            .addComponent(lblDonGiaBan1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDonGiaBan)
                            .addComponent(tfDonGiaNhap)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnResert)
                        .addGap(27, 27, 27)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTimKiem)
                .addGap(39, 39, 39)
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHH)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHH)
                            .addComponent(tfMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenHH)
                            .addComponent(tfTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoLuong)
                            .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGiaNhap)
                            .addComponent(tfDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGiaBan)
                            .addComponent(tfDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonGiaBan1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if(tfMaHH.getText().equals("") || tfTenHH.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        } else {
                    String sql = "INSERT INTO `hanghoa`(`maHH`, `tenHH`, `soLuong`, `donGiaNhap`, `donGiaBan`, `ghiChu`) "
        + "VALUES ('"+tfMaHH.getText()+"','"+tfTenHH.getText()+"','"+ spnSoLuong.getValue()
                +"','"+tfDonGiaNhap.getText()+"','"+tfDonGiaBan.getText()+"','"+taGhiChu.getText()+"')" ;
        excuteQuery(sql, "được thêm");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        String sql = "UPDATE `hanghoa` SET `tenHH`='"+tfTenHH.getText()+"',`soLuong`='"+ spnSoLuong.getValue()
                +"',`donGiaNhap`='"+tfDonGiaNhap.getText()+"',`donGiaBan`='"+tfDonGiaBan.getText()+"',`ghiChu`='"+taGhiChu.getText()+"' WHERE `maHH` = '"+tfMaHH.getText()+"'";
        excuteQuery(sql, "được sửa");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String sql = "DELETE FROM `hanghoa` WHERE `maHH` = '"+tfMaHH.getText()+"'";
        excuteQuery(sql, "được xóa");
        resetText();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        resetText();
    }//GEN-LAST:event_btnResertActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if(DangNhap.cboPhanQuyen.getSelectedItem() == "ADMIN") {
            Admin admin = new Admin();
            admin.setVisible(true);
            this.setVisible(false);
        }
        if(DangNhap.cboPhanQuyen.getSelectedItem() == "NHANVIEN" ) {
            Employee epl = new Employee();
            epl.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jtbQLHHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbQLHHMouseClicked
        int i = jtbQLHH.getSelectedRow();
        TableModel model = jtbQLHH.getModel();
        tfMaHH.setText(model.getValueAt(i, 0).toString());
        tfTenHH.setText(model.getValueAt(i, 1).toString());
        spnSoLuong.setValue(model.getValueAt(i, 2));
        tfDonGiaNhap.setText(model.getValueAt(i, 3).toString());
        tfDonGiaBan.setText(model.getValueAt(i, 4).toString());
        taGhiChu.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jtbQLHHMouseClicked

    private void timKiem(String query) {
        DefaultTableModel model = (DefaultTableModel) jtbQLHH.getModel();
        TableRowSorter<DefaultTableModel> tr =  new TableRowSorter<DefaultTableModel>(model);
        jtbQLHH.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void tfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTimKiemKeyReleased
        String query = tfTimKiem.getText().toLowerCase();
        timKiem(query);
    }//GEN-LAST:event_tfTimKiemKeyReleased

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        String query = tfTimKiem.getText().toLowerCase();
        timKiem(query);
    }//GEN-LAST:event_tfTimKiemActionPerformed

    public void resetText() {
        tfMaHH.setText("");
        tfTenHH.setText("");
        tfDonGiaNhap.setText("");
        tfDonGiaBan.setText("");
        taGhiChu.setText("");
        spnSoLuong.setValue(0);
    }
    public Connection getConnection() {
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_projectjava?useUnicode=yes&characterEncoding=UTF-8", "root", "");
            return conn;
            
        } catch (SQLException ex) {
            Logger.getLogger(QLHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    public ArrayList<HangHoa> getdanhSachHH() {
        ArrayList<HangHoa> dskh = new ArrayList<HangHoa>();
        Connection connection = getConnection();
        String sql = "SELECT * FROM `hanghoa`";
        Statement st;
        ResultSet rs;
        

        try {
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            HangHoa hh;
            while(rs.next()) {
                hh = new HangHoa(rs.getString("maHH"),rs.getString("tenHH"),rs.getInt("soLuong"),rs.getDouble("donGiaNhap"),rs.getDouble("donGiaBan"),rs.getString("ghiChu"));
                dskh.add(hh);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dskh;
    }
      
    //Hàm thực thi các câu truy vấn
    public void excuteQuery(String sql , String message) {
        Connection conn = getConnection();
        Statement st;
        try {
            st = conn.createStatement();
            if(st.executeUpdate(sql) == 1) {
                //Xuất lại jtable sau khi thực hiện truy vấn thành công
                DefaultTableModel model = (DefaultTableModel) jtbQLHH.getModel();
                model.setRowCount(0);
                xuatDanhSachHangHoa();
                JOptionPane.showMessageDialog(rootPane, "Sản phẩm " + message + " thành công");
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Sản phâm không " + message);
            }
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
        public void xuatDanhSachHangHoa() {
        ArrayList<HangHoa> list = getdanhSachHH();
        DefaultTableModel model = (DefaultTableModel) jtbQLHH.getModel();
        Object[] row = new Object[6];
        for(int i = 0 ; i < list.size(); i++) {
            row[0] = list.get(i).getMaHang();
            row[1] = list.get(i).getTenHang();
            row[2] = list.get(i).getSoLuong();
            row[3] = list.get(i).getDonGiaNhap();
            row[4] = list.get(i).getDonGiaBan();
            row[5] = list.get(i).getGhiChu();
            model.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResert;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbQLHH;
    private javax.swing.JLabel lblDonGiaBan;
    private javax.swing.JLabel lblDonGiaBan1;
    private javax.swing.JLabel lblDonGiaNhap;
    private javax.swing.JLabel lblMaHH;
    private javax.swing.JLabel lblQLHH;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenHH;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextArea taGhiChu;
    private javax.swing.JTextField tfDonGiaBan;
    private javax.swing.JTextField tfDonGiaNhap;
    private javax.swing.JTextField tfMaHH;
    private javax.swing.JTextField tfTenHH;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
